# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'gdpr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for gdpr
  pod 'Localytics', '~> 5.1'

  target 'gdprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gdprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
